# In .travis.yml

language: python
python:
  - "3.8"

before_install:
  - nvm install 6.10
install:
  - pip install -r requirements.txt
  - npm update npm -g
  - npm install -g serverless
script: 
  - pytest test_handler.py
  - serverless deploy